#!/bin/bash


git --git-dir=$HOME/.dotfiles --work-tree=$HOME add $@

git --git-dir=$HOME/.dotfiles --work-tree=$HOME diff origin/master

git --git-dir=$HOME/.dotfiles --work-tree=$HOME commit -m "update"

git --git-dir=$HOME/.dotfiles --work-tree=$HOME push origin master
